spring:
  datasource:
    url: jdbc:mysql://azure-mysql-test.mysql.database.azure.com/employees?serverTimezone=UTC
    username: user@azure-mysql-test
    password: Pass1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect